### ISSUE TITLE
[Meta] Repo?

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#10]
I'd be more than happy to maintain a repo for you!

As per your forum post:

> 1. That the repo only contain AZ2 (and maybe horizon genre icon pack) - no 3rd party add-ons etc.

My main suggestion here would be for it to at least contain Marcelveldt's and the Rector Stuff repos, for ease of installation, of you're ok with that.

>  2. That I have editing permissions on the repo.

It would be your repo 👍 Probably the best way is if you make a repo here, and give me access to it. That way I can still do the maintaining, while giving you full access as well.

> 3. That updates are taken from the releases page.

Done 👌

> 4. That updates are made fairly quickly after I make a release (I don't want users to be multiple versions behind because then I will get heaps of bug reports about issues that I've already resolved).

That can also be done. It should only take around five minutes to push an update whenever there's a new release, so I should be able to have them pushed within 24hrs or less.

**Comment by jurialmunkey** [comment]
Sounds great! 👍 

1. A link to install marcelveldt's and rector's repos would be fine. As long as it is not physically duplicating the repo and only providing a link to the zip to install their repos (I'm pretty sure that is what you are suggesting anyway, but just a point to clarify nonetheless!)

2. I've created repository.jurialmunkey and given you collaboration permissions

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/repository.jurialmunkey

**Comment by drinfernoo** [comment]
Sweet beans! I'll get to it in the next few days with the latest release at the time 👍

In response to 1., what you want to avoid is their repo content *showing* in the repo, but rather to just have their repos installable from it? That should be fine if so, as long as they don't change their repos drastically.

**Comment by jurialmunkey** [comment]
1. Yep, exactly.

**Comment by drinfernoo** [comment]
Would it be possible to use the versioning with the `-alphaX` suffix in the addon.xml whenever you put up a new release? That would make my repo a little more sane, I think, since it will be able to distinguish between alpha versions at that point.

**Comment by jurialmunkey** [comment]
Yeah, that's not a problem. It has to use a tilde (~) as the separator though (not sure if that will cause issues in the filename?)
https://kodi.wiki/view/Addon.xml#version_attribute

e.g.
<addon id="skin.arctic.zephyr.2" name="Arctic Zephyr 2" provider-name="jurialmunkey" version="0.9.19~alpha5">

**Comment by drinfernoo** [comment]
@jurialmunkey I think those should be fine.
