### ISSUE TITLE
few skin questions/requests

### ISSUE THREAD

**Issue by kalle2000** [jurialmunkey/skin.arctic.zephyr.2#104]
Hi @jurialmunkey 

I have been using Zephyr 2 since Day 1 and I absolutely love it. Still trying to find out how to use all the features it has Smile

4 Questions where I need guidance:

1) Is PVR artwork already supported by your skin? It seems PVR artwork is downloaded, however it is not displayed anywhere in my setup.
2) For widgets it is possible to define sort method, sort direction and item limit - is it possible to add this for the submenu hub widget, too?
3) Any chance to add an EPG widget for Zephyr2 in any way? Or a widget to support channel groups?
4) Is it possible to show "number of movies / TV shows" and additional info (e.g. playtime etc) next to the other furniture items?

thanks for your outstanding work

kalle

**Comment by jurialmunkey** [comment]
Please ask support questions in the forum thread:
https://forum.kodi.tv/showthread.php?tid=339791

If you have a feature request or bug, please separate them and create individual issues on github with a clear title and description. Otherwise I can't keep track of what needs to be done.
