### ISSUE TITLE
[Request] Disable Search Button on Fixed Width Text Homescreen

### ISSUE THREAD

**Issue by onesane** [jurialmunkey/skin.arctic.zephyr.2#105]
I'd like to be able to disable the magnifying glass search button from the far left on the fixed width test basic home screen view.

**Comment by jurialmunkey** [comment]
Options for changing search button in 0.9.46-a5
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.46-alpha5

Skin Settings > Home > Corner Icon
Options are Search, Power, Settings, Home.

Change to "Home" to disable being able to select the icon.
