### ISSUE TITLE
[Request] "End of Widget" Indicator

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#106]
It would be really nice if there was some type of minimal indicator on the far ends of widgets, so you know when you've reached the end.

It can be very jarring to reach the far-right end of a widget, and be whisked off to the beginning of the list again, and with no "backwards" movement, you've gotta scroll all the way through the widget to get to the end again.

**Comment by jurialmunkey** [comment]
Would this issue be fixed with the addition of horizontal scrolling indicators that only show if there is more content to scroll to.
i.e. would fixing this issue https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/55 also fix your one?

**Comment by jurialmunkey** [comment]
Meta Issue:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/115
