### ISSUE TITLE
[FR] Show channel names in EPG

### ISSUE THREAD

**Issue by ReekyMarko** [jurialmunkey/skin.arctic.zephyr.2#108]
Currently there's no way to see the name of the channels in the guide. I consider this a basic feature of any EPG and it should be added asap.

**Comment by jurialmunkey** [comment]
![Honeyview_screenshot403](https://user-images.githubusercontent.com/4618719/64054969-10acb900-cbcd-11e9-92f0-fcf7f9a316cb.jpg)

Yes, there is.
Skin Settings > PVR >Slim PVR Guide

**Comment by drinfernoo** [comment]
@jurialmunkey Ooh, nice! I didn't realize that was what that did!

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Ooh, nice! I didn't realize that was what that did!

Yeah I really need to get around to adding setting descriptions in skin settings.

**Comment by ReekyMarko** [comment]
Thanks a lot. And yeah, some small description would be helpful. Anyway, this is the best kodi skin by a mile so it's fine :smile:

**Comment by trekker77** [comment]
Is there any way to add EPG to a widget?
