### ISSUE TITLE
[Request] Plot Information with Multiple Widgets

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#11]
Whenever there's no widgets defined for a particular main menu heading, we get some metadata underneath the global widget, like a sort of "spotlight". Is there any sane way to achieve a similar effect with our own widgets, or multiple widgets?

**Comment by jurialmunkey** [comment]
It should work with the first widget set for the menu item. Not possible for multiple widgets currently, however.
