### ISSUE TITLE
[Request] Support for "characterart"

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#110]
I don't believe I've seen a skin that *does* support characterart, but why not??

Finding a place to conveniently display it may be a chore, but I had considered possibly on the OSD, or as a widget.

![This](https://i.imgur.com/CY3HQlL.jpg) "widget" comes directly from Netflix and a similar widget aspect might be a good way to utilize characterart, as even Netflix recommeds that they be used for kid- and family-friendly content.

**Comment by jurialmunkey** [comment]
Character art usually doesn't come in this format for Kodi. Most character art comes from fanart.tv which displays characters against a transparent background:
https://fanart.tv/fanart/tv/81189/characterart/breaking-bad-504b8f08b51c7.png

I don't really understand what the purpose of it is. Plus it is far too inconsistent to use effectively
