### ISSUE TITLE
[Request] Improve notification visibility in OSD

### ISSUE THREAD

**Issue by tadly** [jurialmunkey/skin.arctic.zephyr.2#111]
Especially when watching videos, often times the video content is very bright (or rapidly changes in color) making it difficult (if not impossible) to read a notifications text.

I'd be nice if the notification would have some sort of background to help with readability.

![2019-08-28_14:13:1566994423](https://user-images.githubusercontent.com/503647/63854723-18d2e180-c99e-11e9-964d-9c05d1d003c3.png)

**Comment by jurialmunkey** [comment]
Done:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.49-alpha4
