### ISSUE TITLE
[Feature/Bug] No clock in Music OSD

### ISSUE THREAD

**Issue by tadly** [jurialmunkey/skin.arctic.zephyr.2#117]
Like the title says, there's currently no way to tell the time when in the music osd.
Would be nice if a clock would be added (same place as with video so my eye-muscle memory has an easy time :D)

**Comment by jurialmunkey** [comment]
Added 😀 

https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.52-alpha2
