### ISSUE TITLE
[Request] Fanart Viewer in Information Dialog

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#118]
I really like the way that multiple posters are able to be scrolled through in the Information dialog, as a widget style, or when viewing at full size. Is it possible we could get a similar widget style for fanart as well, or at least the ability to view them at full size? That may mean a different handling of the clearlogo/cdart page, but I would love to be able to see fanart at full size in that view.

**Comment by jurialmunkey** [comment]
Added. Should be able to click on the fanart gallery and get a fullscreen viewer now.
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.51-alpha1
