### ISSUE TITLE
[Request] Support for Extra Artwork on Posters and Thumbnails

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#119]
I'm absolutely loving the implementation of extra fanart backdrops, but am wondering if it would be possible to get similar functionality on landscape and poster views inside the skin. I think it would be pretty obnoxious for them to be autoscrolling, but to have different artwork on a skin reload/refresh might be a really cool feature.

**Comment by jurialmunkey** [comment]
A good idea but not really possible. Extra fanart relies on the Artwork Helper plugin to work and plugins can't be used inside itemlayouts (same reason Skin Helper can't provide info inside itemlayouts).
