### ISSUE TITLE
[Feature Support] Skin Translations

### ISSUE THREAD

**Issue by EffeF** [jurialmunkey/skin.arctic.zephyr.2#12]
Is it possible to use a service like [POEditor ](https://poeditor.com/) or [Transifex ](https://www.transifex.com/) (or similar) to facilitate to users the translation of your skin?

**Comment by jurialmunkey** [comment]
I would prefer to wait until the skin is out of Alpha before people start translating. Many of the strings may change significantly, and many strings may still be added. Once I'm in the Beta stage, I will start looking at translation possibilities.
