### ISSUE TITLE
[Request] Clearart on Video OSD

### ISSUE THREAD

**Issue by DJMix-I-Can** [jurialmunkey/skin.arctic.zephyr.2#121]
Can you add clearart on Video OSD like Aura. I do get clearlogos when I browse my TV Shows & Movies.

Auras' video seek bar with clearart: https://imgur.com/fS0ixJv
Arctics' video seek bar without clearart: https://imgur.com/AU7HgYm
Movies with clearlogo: https://imgur.com/0WIWb7F
TV Shows with clear logo:https://imgur.com/4RnwxFL

 I noticed on Auras' "Includes_Images.xml" file that it has two variables that Arctic doesn't have. They are "Image_Player_Clearart" & "Image_Clearlogo". Another thing I noticed is that on Auras' "Include_OSD.xml" file under "OSD_Video_Seekbar" it does show settings for "Image_Player_Clearart". On Arctic it doesn't. 
Could this be the cause? I tried to add them on Arctic but it didn't work.  I probably missed something.  I have a second issue but will create another post for it.
Thanks.

**Comment by drinfernoo** [comment]
@DJMix-I-Can I've tested your edits, and they seem to be fine, except for a bit of an [overlap with the seekbar](https://imgur.com/l9VaBuE.jpg). I don't really prefer having them there, but if you could tidy that up, I can't see anything else necessarily *wrong*.

**Comment by DJMix-I-Can** [comment]
That's the thing, I did adjust it because I noticed it with Hobbs & Shaw. The feet were on the seekbar, on the other images, they were fine. I'll take a look. Thanks.

**Comment by DJMix-I-Can** [comment]
@jurialmunkey Being that you're currently on right now. I was able to add the clear art but I'm not familiar on how to do a pull request. Can you take a look at the files I edited in order to achieve it.
Thanks.
[AZ2 Clearart.zip](https://github.com/jurialmunkey/skin.arctic.zephyr.2/files/3692861/AZ2.Clearart.zip)
