### ISSUE TITLE
[Support/Bug] Can't add programs on submenu

### ISSUE THREAD

**Issue by DJMix-I-Can** [jurialmunkey/skin.arctic.zephyr.2#122]
On Arctic Zephyr 2 when I try to add Program add-ons as a submenu from the main menu, nothing shows. This is my main menu after I click up for the submenu: https://imgur.com/fsS6j9h

When I go to settings, interface settings, configure skin, home, customize home menu, videos, submenu, programs and select either "Choose Item From menu" or "Action" and select Programs, nothing shows up. I get a blank screen. https://imgur.com/Dtn1Hhg I also retyped it in ,same result. I changed the "colours" for the skin thinking maybe because I have it set to "darker with dark dialogs" could cause it but nothing, I tried everyone of them. I reverted back to the original geometric file because I changed it, nothing. I also deleted the thumbnails folder & textures files, nothing. 
Am I missing something?
Thanks.

OS: Android Nvidia Shield & Windows 7
Skin: Arctic Zephyr 2 Version 0.9.50-alpha3
Kodi 18.4 64bit Windows & Android
Debug log: https://paste.ubuntu.com/p/PPymBpsbF2/

**Comment by jurialmunkey** [comment]
Can you try this version:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.51-alpha2

My guess is that you have the "addons" content type locked to the view "icon wall". However, programs doesn't have that view defined so you end up with a blank view. 

I've added that view to programs, so if this is the issue it should be fixed - let me know if it isn't.

**Comment by DJMix-I-Can** [comment]
I just tried to install it and it failed with the TheMovieDB Helper v1.0.0 dependency error. I don't see that version. So I tried to change the version on the addon.xml file but received a failed due to an invalid structure. Tested it on Windows 7 laptop, that's where my current build is on.

**Comment by jurialmunkey** [comment]
Install TheMovieDB Helper v1.0.0 from my github:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper

**Comment by DJMix-I-Can** [comment]
My apologies, I missed it while viewing your repositories. I installed it and it did work.
Thank you. Should I close it or will you do it.
Thanks again.
