### ISSUE TITLE
[Support/Request] More view types

### ISSUE THREAD

**Issue by DJMix-I-Can** [jurialmunkey/skin.arctic.zephyr.2#123]
Let me start off by saying thanks for the skin and helping me with my other problem.  
I like this skin because I could use that darker with darker dialogues for my interface and it's fast. I was using Aura before this. 
After you added the "Icon Wall" view for programs, I decided to see if I could add different views to it but for the life of me, I couldn't figure it out. 
So this is my problem & actually surprised that no one has mentioned this. 
When I go to video, program & music add-ons, my view type options are only list, square wall & icon wall.
For square wall, the icons are too big. The square wall in Arctic is the size of Square Wall Large in Aura.
https://imgur.com/mpWsiER (On laptop)
https://imgur.com/YWQZwMD  (On Shield)
For comparison, this is square wall on the Aura Skin.
https://imgur.com/nEMsVtu  (On Shield)
https://imgur.com/cMUcst3  (On Laptop)

Since they were too big, I decided to try Icon wall. They are smaller but notice color bleeding and when you select anything the icon will "shrink" to square. Not necessarily shrink but the image stretching reverts to square. Not sure if I'm wording that correctly but here are some pics. The yellow arrows is where the color bleeds.
https://imgur.com/NxxlMcD (On Laptop)
https://imgur.com/VYrX3pQ (On Shield)

This is what happens to the image after selecting an add on.
https://imgur.com/wwllnJO (On Laptop)
https://imgur.com/TPIZDHH  (On Shield)

I also noticed something weird with the Youtube view type. 
On the laptop, my view type options are just list and square wall. Nothing else.
https://imgur.com/eSq9N0o (On Laptop)
On the shield, my view type options are media info, landscape wall, landscape small, landscape showcase & list. No square wall like on the laptop.
https://imgur.com/9tIHOxX (On Shield)

The last thing, is the spinners at home. Can this be hidden? 
https://imgur.com/IcWB2Xm (On both devices)

The skin version I'm using is 0.9.51-alpha6 & Kodi 18.4.
Laptop is Win 7 & Shield is the latest update, 8.0.1
It happened on an existing Kodi setup and a fresh install.
I did uninstall the skin and made sure I removed the addon data folder before I re-installed it. I also tried the square theme but to be honest, I saw no difference with it compared to the skin default..
If you could add that square wall from Aura or add Square small I would appreciate it. 
Let me know if you need any more info.
Thanks

**Comment by jurialmunkey** [comment]
I've been meaning to fix the busy spinner issue on home screen for a while. Should be fixed now:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.52-alpha1

There are spacing issues with a smaller square wall view (3 rows) because the vertical spacing has to be greater than the horizontal spacing between items, but the vertical gap is not large enough to fit a label in to balance out the view. As much as possible I try to maintain a 40px padding between items (or use text to balance out the spacing), so that's why there isn't a small square view. The icon wall view exists because of this issue. However, it's got its own issue as kodi doesn't typically have a landscape aspect icon for addons. 

So, instead, I try to fake it by stretching the sides of the icon out - but, as you can see by the bleed, it's pretty hacky at the moment because the skinning engine doesn't give me much control. I'm hoping in the future we will have two different icon types (square & landscape) for add-ons, as landscape icons are pretty standard for most smart tv interfaces now.

**Comment by jurialmunkey** [comment]
![Honeyview_screenshot428](https://user-images.githubusercontent.com/4618719/66450962-2fdd1700-eaa6-11e9-9c1e-6aaf364b3187.jpg)

You can see the spacing issue in this screenshot - the vertical padding doesn't match the horizontal padding, but there isn't enough space to fit a label to balance it out - either the label will be below the defined view area (red line) or the vertical padding is reduced to fit the labels within the view area but then there isn't enough padding to fit the label without cramping the view.

**Comment by DJMix-I-Can** [comment]
I understand. As for the landscape view on Smart TV interfaces, I'm not a fan of it. I guess that's why it irks me. As for the labeling per your screenshot. What's your thought on putting the title on top in the middle as you scroll through the addons. Like in the posters for TV/Movies, minus the test underneath the icons. Thanks
<blockquote class="imgur-embed-pub" lang="en" data-id="P1VKwyI"><a href="//imgur.com/P1VKwyI">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by DJMix-I-Can** [comment]
I tweaked the View_510_Wall_Square setting in the Includes_View_51_Wall file. I tweaked and added itemheight to it.
<param name="itemwidth" value="255" />
<param name="itemheight" value="280" />
<param name="iconheight" value="245" />
As for the aspect ratio, I kept it at "keep" but could also do "scale", user preference I guess.
I was able to get it to my satisfaction. https://imgur.com/0MXFPHR
In regards to the padding scheme you mentioned, is that the reason I get that extra row once I reach the end of the video addons? https://imgur.com/jEeJCoB
It's not an issue for me, just curious.  Besides the padding issue you mentioned, is there anything I should look into? Thanks again...

**Comment by jurialmunkey** [comment]
>
>
> is that the reason I get that extra row once I reach the end of the video addons?

The entire height of the panel is not high enough for three full rows. For instance if your itemheight is 280px then you need a panel height of 840px to fit three rows properly. However, default panel height in the skin is 825px (780px viewing space + 40px item padding + 5px to prevent text descenders being cut-off) and so there isn't enough space to move to the third row.
