### ISSUE TITLE
[Bug] Reloading Skin Resets "Menu style" and "Widget movement"

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#128]
Just as the title says. It seems that reloading the skin resets those two settings... I've just never noticed it in my main setup because I use them as defaults!

**Comment by drinfernoo** [comment]
You know... I was seeing this in a test environment while working on a PR to the skin, but am unable to reproduce it on my main setup. I'll close this, as I'm pretty sure it's my fault.

**Comment by jurialmunkey** [comment]
What do you mean by "reloading the skin"?

Reload skin doesn't reset these settings for me. They are just standard skin settings like all the others, so there is no reason why they would reset.

Maybe your guisettings haven't been written correctly. Try setting your settings and then exit kodi using the powermenu (don't force quit or Alt+F4 etc.).

**Comment by drinfernoo** [comment]
I dunno... I've tried this in a couple different test environments, but I can't get consistent results. I'm suspicious it has something to do with the edits I've made, but they shouldn't be touching this, so I'm not sure.
