### ISSUE TITLE
[Request] Lyrics icons and settings on music OSD

### ISSUE THREAD

**Issue by Yaminoyuurei** [jurialmunkey/skin.arctic.zephyr.2#132]
There aren't any settings or icons for Lyrics on music OSD.

**Comment by peat80** [comment]
I would request this myself too. Would be nice if we could disable lyrics by default and just activate it on demand via music osd.

**Comment by jurialmunkey** [comment]
Added:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/0.9.54-alpha4
