### ISSUE TITLE
[Request] Dismissable OSD

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#133]
In Estuary, a tap on the screen during playback shows the OSD, while a second tap hides it.

Is it possible for us to get this behavior?

**Comment by jurialmunkey** [comment]
Yep. Easy to add - just didn't realise that Estuary had that feature because I rarely use the mouse.

Added here:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/0.9.54-alpha3
