### ISSUE TITLE
Request: Lighter and larger text on non highlighted items.

### ISSUE THREAD

**Issue by vvPROJECT** [jurialmunkey/skin.arctic.zephyr.2#137]
I have poor eyesight and am struggling to see the grey text on a dark background, particularly the text underneath widgets. A lighter shade of grey would really help, the option to pick my own don't colors would be perfect.

Also on the original AZ I used to be able to set the text to large Ariel to help me see it better. On AZ 2 there are no font options, just the option to zoom in which I have done. Thankyou

**Comment by michaelarnauts** [comment]
I would also like that. I use the light color setting (the default), but maybe a version with more contrast can be added where the text color is more black instead of gray. The info text of a selected broadcast in the PVR Guide is especially hard to read.

**Comment by jurialmunkey** [comment]
You can edit the colour scheme in the folder skin.arctic.zephyr.2/colors/ 

See the defaults.xml file for all definitions:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/blob/master/colors/defaults.xml

Names should be fairly straight forward. Skin defines a bg and a fg colour and then also provides a variety of different opacities for that colour (e.g. main_fg_100 and main_fg_70 etc)

Colors are in the format AARRGGBB  
`<color name="main_fg_100">ff333333</color>`  
Change the ff333333 part to change the colour for that definition.
