### ISSUE TITLE
[Request] Lists on People Information

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#139]
When browsing People in the TMDb sections of TheMovieDb Helper, they have cast and crew lists available. Can these be displayed on the Information dialog for People?

**Comment by jurialmunkey** [comment]
They already are ...

![Honeyview_screenshot445](https://user-images.githubusercontent.com/4618719/69714905-6ad10200-115b-11ea-91ef-43353d60a0bf.jpg)

![Honeyview_screenshot446](https://user-images.githubusercontent.com/4618719/69714904-6ad10200-115b-11ea-9f32-20f582df2bff.jpg)

![Honeyview_screenshot447](https://user-images.githubusercontent.com/4618719/69714902-6ad10200-115b-11ea-9998-43d3d6c64eee.jpg)

**Comment by drinfernoo** [comment]
Oh, strange. I'm unable to scroll down to those lists 🤔
