### ISSUE TITLE
[Request] Allow Focus and Options for Weather Widget

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#14]
In Aura (and maybe AZ1?), you can focus the Weather widget on the home screen in order to access Kodi's Weather service settings, change the fanart and icons, and manually refresh the weather information. Could we get those features in AZ2?

**Comment by jurialmunkey** [comment]
Added to my todo list.

**Comment by jurialmunkey** [comment]
Added https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/61230f766a4a4b8c5a65fe7d2f653a97c242ab86

**Comment by drinfernoo** [comment]
This didn't add the "top menu" to change the options for the widget display, did it?
