### ISSUE TITLE
[Bug?] "Play" Option not Available in DialogVideoInfo on non-Library Items

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#145]
It doesn't appear that the new player functionality of TMDbHelper is able to be used in the info dialog of AZ2 yet? I don't see any option to play/search based on the player files.

**Comment by jurialmunkey** [comment]
Just haven't got to adding it yet. 😉

**Comment by notoco** [comment]
Works!

**Comment by jurialmunkey** [comment]
It seems that it already works with latest versions of the plugin without any needed changes.

**Comment by drinfernoo** [comment]
Ah, it does appear to! My bad 😁

**Comment by notoco** [comment]
I still don't see it. I just have a browse/search/cast. Search leads to global search
![screenshot000](https://user-images.githubusercontent.com/36659110/70375271-07359a00-18fc-11ea-84ea-36f535319f74.png)

 TMDbHelper - today from git 1.0.30
Skin - from official repo, default settings, the same with version form git...

**Comment by drinfernoo** [comment]
You have to select the video file inside the section for the item you're trying to play.

**Comment by notoco** [comment]
so what, I search for a movie and instead of entering information I go in and play it there (it works).

**Comment by drinfernoo** [comment]
What's missing for me is the ability to play a file using a player file, when that item is *from* a different add-on.
