### ISSUE TITLE
Option to remove 'Now Playing' from main menu

### ISSUE THREAD

**Issue by Joostzilla** [jurialmunkey/skin.arctic.zephyr.2#15]
When playing video 'Now Playing' text appears at the top of the main menu (vertical menu)
For me this is distracting.
Is it possible to remove this?

**Comment by jurialmunkey** [comment]
Screenshot? Sounds like a bug...

**Comment by Joostzilla** [comment]
Coming up

**Comment by jurialmunkey** [comment]
Looks like an issue with your skinshortcuts setup. 

In the home customisation screen for main menu, what is the first item?

**Comment by Joostzilla** [comment]
TV/Radio

**Comment by jurialmunkey** [comment]
It looks like you have an item in the first position with $INFO[Player.Title]
Either way, if this happens in other skins then it isn't an AZ2 specific issue.

**Comment by Joostzilla** [comment]
Is this something i can fix myself?

**Comment by Joostzilla** [comment]
Fixed it. Thanks for your help. You are the best :-)
