### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by 7E1EVEN** [jurialmunkey/skin.arctic.zephyr.2#150]
If your device has multiple CPU threads, the memory usage is cut off when viewing player process info.

Example:
![3FD39AD0-3F92-4593-B330-573A3A31ECE5](https://user-images.githubusercontent.com/52139027/71542504-87817500-2967-11ea-8403-6b07403e7b3b.jpeg)

**Comment by jurialmunkey** [comment]
Should be fixed in latest release https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/9509f88e1f500fee8a7c58576d5cb1be0f337f62

**Comment by 7E1EVEN** [comment]
This is solved. I can see the RAM usage now.

Thank you very much. You're awesome!
