### ISSUE TITLE
[Bug?] "Basic" Home Layout doesn't Build Skin Shortcuts

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#155]
I'm not sure if this a bug or by design... but when using the "Basic" homescreen layout, Skin  Shortcuts `.DATA.xml` files are not built for the defined background widgets.

I'm currently using those files for the functions of my new add-on, AutoWidget, but since they aren't present, it isn't possible to use my widgets in "Basic".

All of this works perfectly fine in both "Vertical" and "Horizontal" layouts.

**Comment by jurialmunkey** [comment]
That's because in Basic layout I use the standard method of building widgets with skinshortcuts which attaches the widget properties to main menu listitems.

The method I use for Multi Widget layout in AZ2 is **NOT** used by any other skin (afaik) and differs significantly from the normal approach skins use for widgets with skinshortcuts. My method for multi widgets is actually a hack that re-purposes submenu item templates rather than setting properties

If your addon doesn't work with the Basic layout, then I would caution you to avoid traveling further down the path of your current approach as that means it is unlikely to work with the vast majority of skins.

**Comment by drinfernoo** [comment]
So are they written directly to the `script.skinshortcuts-includes.xml`, skipping the `.DATA.xml` files entirely?

**Comment by jurialmunkey** [comment]
Yep

**Comment by jurialmunkey** [comment]
Here's an example of a mainmenu item from mine:
```xml
<include name="skinshortcuts-mainmenu">
	<item id="1">
		<property name="id">$NUMBER[1]</property>
		<label>$LOCALIZE[20342]</label>
		<label2>Custom item</label2>
		<icon>special://skin/extras/icons/film.png</icon>
		<thumb />
		<property name="labelID">20342</property>
		<property name="defaultID">movies</property>
		<property name="widget.backgroundWidget">RandomMovies</property>
		<property name="widgetName.backgroundWidget">31200</property>
		<property name="widgetType.backgroundWidget" />
		<property name="widgetTarget.backgroundWidget">videos</property>
		<property name="widgetPath.backgroundWidget">special://skin/extras/playlists/RandomMovies.xsp</property>
		<visible>Library.HasContent(Movies)</visible>
		<onclick>ActivateWindow(Videos,videodb://movies/titles/,return)</onclick>
		<property name="path">ActivateWindow(Videos,videodb://movies/titles/,return)</property>
		<property name="list">videodb://movies/titles/</property>
		<visible>String.IsEqual(System.ProfileName,Master user)</visible>
		<property name="submenuVisibility">num-20342</property>
		<property name="group">mainmenu</property>
		<property name="hasSubmenu">True</property>
	</item>
[...]
</include>```

The name of the include and the name of the widgets is up to the skinner. There may also be widgets attached to various other sub menus and custom menus

**Comment by jurialmunkey** [comment]
For your plugin to work correctly, you need to provide a plugin path that directly provides the items via the plugin path without injecting code into shortcut templates. You need to make sure it works by opening in via video add-ons -- that will ensure cross-skin compatibility.

Have a look at the "Files.GetDirectory" JSON-RPC method that I use in the TMDbHelper Player function to walk the folder paths of a kodi directory. https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/kodilibrary.py#L246-L255

What you could do is have a plugin path that picks one of its predefined paths at random and then uses JSON-RPC getdirectory method to get the infolabel details for that path. You can then pass those onto a listitem and build the container.

Other option is that you set skinstrings/window-properties with the path as you are doing now, and then have users input these manually into skinshortcuts as the path to a widget.

**Comment by drinfernoo** [comment]
@jurialmunkey I did go about trying to do that by listing the directory... But found that metadata and context menus would be missing unless I could fully rebuild each ListItem in the directory, which I wasn't keen on.

If you haven't tried it out yet, you should check out AutoWidget. You can get the development repo from https://drinfernoo.github.io/ 😁 I'm honestly pretty happy with the way it's working, and seems to work well in pretty much every skin I've tried. I was even able to get it working with your "Basic" layout... which hopefully has fixed it for other skins too 👍

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey I did go about trying to do that by listing the directory... But found that metadata and context menus would be missing unless I could fully rebuild each ListItem in the directory, which I wasn't keen on.

Fair enough -- definitely less than ideal if you can't get all the metadata.

> 
> 
> If you haven't tried it out yet, you should check out AutoWidget. You can get the development repo from https://drinfernoo.github.io/ 😁 I'm honestly pretty happy with the way it's working, and seems to work well in pretty much every skin I've tried. I was even able to get it working with your "Basic" layout... which hopefully has fixed it for other skins too 👍

Well if it is working with other skins, then it is working with other skins, so no need for a different method then!

Yeah I checked it out. Seems to work well! Had some trouble getting it to work initially - setup was easy enough (though a little confusing about what path to set as the widget). I just had trouble getting it to actually work despite having correctly set up the widgets - needed to do a few restarts and force refreshes.

I also got some errors when I deleted a group that was being used as a widget.

**Comment by drinfernoo** [comment]
I think I've ironed out all those issues you've mentioned, actually! Would love some further testing as well, as I've hopefully added enough "convenience" items to the menus to make it a bit clearer which directories do what.

Also, in [this issue](https://github.com/drinfernoo/plugin.program.autowidget/issues/1), I've laid out some issues I'm having with the custom window I'm using, and paged you for help :rofl: I invited you to be a contributor, if you'd like, but if not, that's fine as well. As I've always said, you're the king of skins... so I'd be honored to get some help!

**Comment by jurialmunkey** [comment]
I had these same issues with most recent version from your repo (0.0.18 iirc). Unless there has been an update since?

**Comment by jurialmunkey** [comment]
The part I found confusing was the label "Point a widget at this directory ..." -- I wasn't sure if I was supposed to click that item first or just directly click the "use as widget".

Might be easier to understand if you have a separate folder called "Widgets" and inside that is just direct links to the groups that the user had created with nothing else.

**Comment by drinfernoo** [comment]
@jurialmunkey Ooh, I actually really like that! I may work something like that out.

0.0.118 is pretty recent, but I thought I had gotten things working a little better 😩
