### ISSUE TITLE
Option to change the transparency of the highlight white color in TV guide

### ISSUE THREAD

**Issue by Joostzilla** [jurialmunkey/skin.arctic.zephyr.2#16]
The White highlight color is nice but i would like to tone it down a bit in the TV guide and List views.

**Comment by jurialmunkey** [comment]
This can be done with colour schemes. Once the skin is out of alpha, I will provide people with instructions on how to edit colour schemes.

**Comment by Joostzilla** [comment]
Great. Thanks a lot :-)
