### ISSUE TITLE
Ratings not updating

### ISSUE THREAD

**Issue by LTLNEMO** [jurialmunkey/skin.arctic.zephyr.2#17]
I'm not getting IMDB or RT ratings. They are enabled in the preferences but not appearing in Kodi or in the Edit metadata fields

**Comment by drinfernoo** [comment]
Have you entered your OMDB key in script.module.metadatautils as outlined in the forum post?

**Comment by LTLNEMO** [comment]
I’m getting IMDb and TMDB after a metadata refresh. I’ll try your recommendation. I’m thinking it might actually be something on the NFO end since I’m using local scraping only

**Comment by jurialmunkey** [comment]
Doesn't work with scraped data. Need either skinhelper or listitemhelper for additional ratings to work. Kodi doesn't provide a way to access scraped additional ratings outside of the info dialog and there is currently a bug in core which prevents checking whether or not a rating is already available in db. So skinhelper or listitemhelper are currently the only solutions.
