### ISSUE TITLE
[Request] Long Press Subtitles on OSD to Download

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#171]
Simple, I'd love it if a long-press on the subtitle icon on the OSD would bring up the download dialog.

I often get subtitles that are out of sync, and it's easier to just try another set than to "sync them up", but once subtitles are available, clicking that button only turns them on and off.

**Comment by jurialmunkey** [comment]
There's no <onlongclick> action in the skinning engine, so unfortunately not possible.
