### ISSUE TITLE
I only get a blue spinning ball after installing this skin :(

### ISSUE THREAD

**Issue by boza111** [jurialmunkey/skin.arctic.zephyr.2#176]
Hello my friends,

I am trying to get this to work on Kodi 18.5 on Mac OS. I tried cloning the skin and copying it into the addon folder. When I activate it in Kodi it asks if I want to keep the skin changes. When I press yes I only get a spinning blue ball. Restarting Kodi doesn't help.

Am I doing something wrong? Am I missing a dependancy?

**Comment by drinfernoo** [comment]
Follow the official install instructions from [the forum](https://forum.kodi.tv/showthread.php?tid=339791).

**Comment by brentonv** [comment]
Use the built-in skin backup tool. It collects all the required files for restore.

**Comment by drinfernoo** [comment]
@brentonv How is that relevant here?

**Comment by brentonv** [comment]
Figured it was this bit " I tried cloning the skin and copying it"

**Comment by brentonv** [comment]
Sorry figured it was this bit " I tried cloning the skin and copying it" I assumed op was copying the skin userdata and not working.

**Comment by drinfernoo** [comment]
The solution here is to follow the install instructions.

**Comment by jurialmunkey** [comment]
> Am I missing a dependancy?

Yes.

Most likely skin shortcuts.
