### ISSUE TITLE
Incorrect label

### ISSUE THREAD

**Issue by taoxtrece** [jurialmunkey/skin.arctic.zephyr.2#178]
https://github.com/jurialmunkey/skin.arctic.zephyr.2/blob/f801c2eca30f88238f6d6bc1c8ce24368df97a10/1080i/script-upnext-upnext.xml#L46

correct... 

`<label>$ADDON[service.upnext 30037] [COLOR $VAR[ColorHighlight]][/COLOR]...</label>`

**Comment by taoxtrece** [comment]
and in script-upnext-stillwatching.xml
`<param name="label" value="$ADDON[service.upnext 30010] $ADDON[service.upnext 30036] [COLOR $VAR[ColorHighlight]]$INFO[Player.TimeRemaining(ss),,][/COLOR] $ADDON[service.upnext 30035]" />`
correct...
`<param name="label" value="$ADDON[service.upnext 30035] [COLOR $VAR[ColorHighlight]]$INFO[Player.TimeRemaining(ss),,][/COLOR]" />`

**Comment by drinfernoo** [comment]
There not a "call" being made here... Those are labels, set with the proper format for string localization in Kodi. All you've done here is remove pieces of the labels the Up Next provides.

**Comment by taoxtrece** [comment]
yep i know i can read label sorry for my english mistake but change the label solved the issue

**Comment by drinfernoo** [comment]
What's the issue? There should be nothing wrong with those labels.

**Comment by taoxtrece** [comment]
https://raw.githubusercontent.com/im85288/service.upnext/master/resources/language/resource.language.en_gb/strings.po

**Comment by drinfernoo** [comment]
I've opened a PR to fix these :+1: Thanks for the heads up... kinda weird I didn't notice them 😆

**Comment by taoxtrece** [comment]
Great!👍
