### ISSUE TITLE
[Request] Option to set blur amount

### ISSUE THREAD

**Issue by Joostzilla** [jurialmunkey/skin.arctic.zephyr.2#18]
In Aura the settings for blur are excellent. Do you have any plans to add that to AZ2

**Comment by jurialmunkey** [comment]
Not the full set of options, but definitely an option to change blur amount.

**Comment by jurialmunkey** [comment]
Added in 0.9.46
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.46-alpha1
