### ISSUE TITLE
[Request] Multiple Widgets Per Submenu Items in Submenu Hub

### ISSUE THREAD

**Issue by Syco54645** [jurialmunkey/skin.arctic.zephyr.2#183]
I am trying to declutter my home screen by adding an Overflow/More section of sorts. I can sort of accomplish this with submenu hubs but would also like a few widgets (or even one) per submenu items. Would this be something that is easily accomplished?

**Comment by drinfernoo** [comment]
> but would like a few widgets (or even one) per submenu items

You can accomplish this now. Each submenu item can have a widget be displayed when it is focused. For example, I have a submenu item for my Trakt Watchlist, and when focused, it shows a widget of my other Trakt lists.

**Comment by jurialmunkey** [comment]
Yeah, you can already do this. You need to enable the "Replace submenu with hub" option to see the widget options in the home customisation menu

**Comment by Syco54645** [comment]
> Yeah, you can already do this. You need to enable the "Replace submenu with hub" option to see the widget options in the home customisation menu

Is there a way to have multiple widgets per submodule entry?

**Comment by drinfernoo** [comment]
@Syco54645 No, not at this time.
