### ISSUE TITLE
Up Next Notification Message

### ISSUE THREAD

**Issue by weebl101** [jurialmunkey/skin.arctic.zephyr.2#184]
Hello,

When using the newest version of UP Next the notification that appears at the end of a episode is bugged. Log: https://drive.google.com/open?id=1C5_i7HyMTEacmNs3GSStVK68PWr8VVvm

It says:

Up Next Up Next in 12 seconds 12 Continue watching in 12 Seconds...

Screenshot attached.

Thanks in advance.
![33392749-C02F-4241-8C84-141C798FDF6D](https://user-images.githubusercontent.com/7332213/74720627-ce159080-5281-11ea-9585-c08d24791073.jpeg)

**Comment by notoco** [comment]
I told you elsewhere - the bug is fixed, download the github version and enjoy the working add-on.

**Comment by weebl101** [comment]
The version on github is 2 months old, version 0.9.55 - there has been another released since then, 0.9.58 - could the bug have reemerged??

**Comment by notoco** [comment]
The version on github is https://github.com/jurialmunkey/skin.arctic.zephyr.2/blob/master/addon.xml 0.9.58-alpha1 - and 6 days ago the patch https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/fb595aad78eac8142fb1a1e83ba52876732d16d7
 Download the github version and install it. Simple

**Comment by weebl101** [comment]
ah ok, sorry. I am using drinfernoo repo, and thought that had been updated to. Thank you again for your help.
