### ISSUE TITLE
[Request] More than 25 items in submenus widgets

### ISSUE THREAD

**Issue by PrevotYann** [jurialmunkey/skin.arctic.zephyr.2#185]
Hey man !

First of all, thank's a lot for your job, loving AZ2 so far on my Shield TV and PCs ! :)

I was wondering if you could se an option to show more than 25 items in submenus widgets ? I got one with loooots of things, so It would be great :)

Again, thank's a lot in advance haha

**Comment by jurialmunkey** [comment]
There's an option in the widget customisation dialog to change the limit...

**Comment by PrevotYann** [comment]
![image](https://user-images.githubusercontent.com/48239947/75076043-6cfaf080-54ff-11ea-9e62-cb582045f583.png)

Sorry but I do not find it, is this in another place ? (sorry if for noobies question haha)
