### ISSUE TITLE
[Bug] PVR Player's button not working

### ISSUE THREAD

**Issue by botallen** [jurialmunkey/skin.arctic.zephyr.2#186]
PVR player's playback button not working (stop,next)

**Comment by drinfernoo** [comment]
Is it working for you in other skins?

**Comment by botallen** [comment]
It's strange bug sometimes works and sometimes don't. I'm currently using it in windows 10 and on first time i open any pvr channel then it's not working but moving to main menu and after playing any pvr channel then it's working

**Comment by botallen** [comment]
![Capture](https://user-images.githubusercontent.com/60690413/75116283-ab71e600-568c-11ea-9dc9-bddf5345859d.JPG)

I just noticed it's working in below button area so must be some styling problem.
See in image
