### ISSUE TITLE
Menu Style "Icons + Text" not sticking

### ISSUE THREAD

**Issue by nicgentile** [jurialmunkey/skin.arctic.zephyr.2#188]
Been testing your skin, excellent stuff. 
I have the Home Layout as Vertical Menu|Multiple Widgets.
When I set the menu style to Icons + Text, on the next reboot, it goes back to just text.

While its on, my fix is to go back and change the Menu Style back to Icons + Text then reload the skin, then they appear.

**Comment by drinfernoo** [comment]
Hmm, I haven't seen this happening, and I use that menu style 🤔

**Comment by nicgentile** [comment]
I'm currently working on my 3rd build of the same and the result is the same. Could it be a Kodi build issue? I'm running Alexelec 3.1.8 with Kodi 18.5 Git.

**Comment by jurialmunkey** [comment]
You need to exit kodi properly (i.e. from shutdown menu) rather than just pressing the power button.
