### ISSUE TITLE
Show begin and end time in second line TV Guide (like Aura)

### ISSUE THREAD

**Issue by Joostzilla** [jurialmunkey/skin.arctic.zephyr.2#19]
Could you make the second line in the TV Guide an user option between showing 'Programme Characteristics' or 'Programme begin-end time'?

https://imgur.com/RuVB3Ub

**Comment by jurialmunkey** [comment]
On my todo list.

**Comment by Joostzilla** [comment]
Thanks a lot

**Comment by jurialmunkey** [comment]
Added https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/fc795023f657ae55b3432b5648c70987f953816f
