### ISSUE TITLE
[Request] Touchscreen Compatibility

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#2]
At this time, it seems impossible to scroll home screen widgets or access submenus on a touchscreen... Is it possible this could get added in the future?

**Comment by jurialmunkey** [comment]
Touch/Mouse scrolling between list containers in a grouplist doesn't even work in Estouchy, and that is the default skin dedicated to touch support. It's just a kodi limitation unfortunately.

I don't really have any solutions for this issue - so if you know of any skin that handles this well, please let me know so I can see how they have done it. 

BTW - If you are using touch, I recommend setting your home menu items to open submenu hubs by setting their action to "ActivateWindow(1135)" (there is a shortcut to this under "Common").

**Comment by SerpentDrago** [comment]
> BTW - If you are using touch, I recommend setting your home menu items to open submenu hubs by setting their action to "ActivateWindow(1135)" (there is a shortcut to this under "Common").

Thank you ! this helps me on other things unrelated ! saved me from having to lookup the custom action

**Comment by drinfernoo** [comment]
@SerpentDrago We also talked a bit about the others available in #7.
