### ISSUE TITLE
Persistance in Skin Options

### ISSUE THREAD

**Issue by nicgentile** [jurialmunkey/skin.arctic.zephyr.2#200]
This is related to this [issue](https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/188) I opened up about a month ago.
Now hear me out please. If you kill the device before logging off, some skin settings get lost. The settings.xml file in the skin folder addon data don't seem to do much. The problem is, I live in a country where we can get up to 3 power outages every single day, every day. So, while you can't plan for outages, having to reset the skin every single time kinda becomes a task. Surely, there must be a way to make the settings stick.

**Comment by jurialmunkey** [comment]
Nothing can be done from the skin side of things. The only "solution" would be to exit kodi after you make changes to settings and then reopen it.

From memory, I think if you call the ReloadSkin() function is will also save the skin settings.
