### ISSUE TITLE
Option to not go to Music Now Playing screen when starting a track

### ISSUE THREAD

**Issue by Joostzilla** [jurialmunkey/skin.arctic.zephyr.2#22]
When starting a track Kodi goes directly to the Now Playing screen. Is it possible to make this a user option (if this skin related of course)

**Comment by jurialmunkey** [comment]
Kodi doesn't do this by default.
Are you sure you haven't enabled "Skin Settings > Video / Music > Automatically open visualisation after starting a song"?

**Comment by Joostzilla** [comment]
No this option is disabled. Strange
