### ISSUE TITLE
Clearlogo in the Movie Section

### ISSUE THREAD

**Issue by kkoobbi** [jurialmunkey/skin.arctic.zephyr.2#226]
hi,
is there any chance how i can display clearlogo of a movie in the movies section. im using the poster wall and tried to add the clearlogo by myself with no luck

**Comment by drinfernoo** [comment]
![](https://i.imgur.com/Pk9zA3M.jpg)

**Comment by kkoobbi** [comment]
@drinfernoo i did had this option enabled. i also on/offed with no luck. plus, in the poster fanart choosing, there isnt any clearlogo option. you can only add a picture with a name

**Comment by drinfernoo** [comment]
You need to use something like Artwork Beef to add artwork to your library items, then... or curate your own.

**Comment by kkoobbi** [comment]
@drinfernoo omg it did work. Thank you mate
