### ISSUE TITLE
[Bug] Date in TV guide is cut off

### ISSUE THREAD

**Issue by Joostzilla** [jurialmunkey/skin.arctic.zephyr.2#23]
https://imgur.com/w1tIuQ2

**Comment by jurialmunkey** [comment]
Yeah I know about this one. Doesn't seem to be anything I can do about it - Kodi forces the date label to be the same width as the channel layout.

**Comment by Joostzilla** [comment]
Maybe you can use a different date format. Like 03-04-2019
Or... Add the date to the title: TV Guide of Thursday 4th 2019

**Comment by jurialmunkey** [comment]
Can't change it unfortunately. Forced by Kodi in the timeline control of the EPG.

**Comment by Joostzilla** [comment]
And make it scroll?
