### ISSUE TITLE
Automatically switch color theme stopped working

### ISSUE THREAD

**Issue by benkap** [jurialmunkey/skin.arctic.zephyr.2#231]
Hey, I've noticed that few days (maybe weeks) ago this feature stopped working but I haven't found a single post/issue/comment about it.

I'm running:
Intel NUC - Libreelec 9.2.3
KODI 18.7
Skin: 0.9.62

I also can't find anything related to arctic.zephyr.2 in logs on debug or with specific logging... 
Let me know if there is more information I can send you.

Great work on this skin.. It makes Kodi

**Comment by drinfernoo** [comment]
If you haven't already, you need to install Skin Helper Service (script.skin.helper.service) from `Skin Settings -> Manage dependencies`.

**Comment by benkap** [comment]
I did checked that all the dependencies are installed but you gave me an idea and I forgot that marcelveldt repo was disabled so maybe I've missed an update. I saw that I had the 3.0.0 version where marcelveldt use 1.1.24. But after reinstalling both and restarting Kodi each time I don't get the Dark Mode still.

**Comment by drinfernoo** [comment]
The conditions that control the switch are:

```<onload condition="Skin.HasSetting(ThemeSwitcher) + System.Time(06:00,18:00) + !String.IsEqual(Skin.CurrentColourTheme,SKINDEFAULT)">XBMC.RunScript(script.skin.helper.service,action=setkodisetting,setting=lookandfeel.skincolors,value=SKINDEFAULT)</onload>
<onload condition="Skin.HasSetting(ThemeSwitcher) + !System.Time(06:00,18:00) + !String.IsEqual(Skin.CurrentColourTheme,Dark)">XBMC.RunScript(script.skin.helper.service,action=setkodisetting,setting=lookandfeel.skincolors,value=Dark)</onload>```

Meaning that the skin will switch to the "Default" theme as long as the setting is on, your local time is between 6:00am and 6:00pm, and you're not already using the default theme. Conversely, the "Dark" theme will be used when the setting is on, the time is between 6:00pm and 6:00am, and you don't already have the dark theme selected.

When those conditions are met, Skin Helper is called on to change the corresponding setting.

Is the setting enabled? Is it the proper time? Are you already using the theme it should be switching to? Can you see anything in your log indicating that Skin Helper isn't working?

**Comment by benkap** [comment]
- I confirm that the settings is enabled (i disabled and re-enabled multiple times each time restarting Kodi to troubleshoot) 
 - I confirm that between 6PM and 6AM (looking at Kodi's/LibreElec clock) I still have only the "light" theme
 - Only now I found out that I can change them manually :) The settings is "Skin Default" I think it always stayed like this (it worked great till X days ago).
 - In logs zero msg from 'Skin Helper'. There are few script.colorbox errors like: 
` NOTICE: script.colorbox: go_mapof: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/script.colorbox/fa645dc466a124f0a550e76191ae02f61.0-blur304.png' ops: common/null.png` But afaik they are not related or is it? I did saw the script.colorbox NOTICE many times before... I had a problem with version 3.0.0 where it would creash each time Kodi starts but with 1.2.24 no errors unfortunately not even with debug enabled.

**Comment by drinfernoo** [comment]
Which add-on are you having issues with 3.0.0?

The script.colorbox errors are related to background blur, unrelated to this, and not a breaking error.

**Comment by benkap** [comment]
3.0.0 for the "Skin Helper", not sure from which repo. It basically didn't worked and is suspicious  when I saw it due to your comment I switched to marcelveldt 1.2.24 all the old errors (error on Kodi startup from skin helper) stopped and the logs are now clean but still no Dark Theme...

**Comment by drinfernoo** [comment]
@benkap I'll attempt to reproduce this at some point, but it works as far as I know.

**Comment by benkap** [comment]
Interesting... I left the settings off since 5 days ago and turned it and got the dark theme as I used to get. I guess something in all the reinstalling/cleaning did the job. Thanks again for this amazing UI
