### ISSUE TITLE
Star rating and "No information available" showing at main menu

### ISSUE THREAD

**Issue by Odeni** [jurialmunkey/skin.arctic.zephyr.2#24]
When navigating main menu, empty star rating and "No information available" is showing. Can this be removed?

![Capture](https://user-images.githubusercontent.com/9049328/55502044-000f0b80-564c-11e9-8a1a-ff2bff4d5a6b.PNG)

**Comment by jurialmunkey** [comment]
Fixed https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/105f5cb0fbb622b24890cb95d570f393d97aa40a
