### ISSUE TITLE
[Request] Browse Icons

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/skin.arctic.zephyr.2#245]
@jurialmunkey thanks again for this incredible skin it's truly amazing. I just have a small request if it's possible, could you please consider adding an option for browsing icons outside of the folder root `special://skin` 

Thanks mate

**Comment by drinfernoo** [comment]
Just browse "back" from the normal icons.

**Comment by brentonv** [comment]
@drinfernoo "Just browse back from the normal icons" yeah how strange that worked fine on my Amazon device. For some reason it's locked to the folder root on my Android-x86 install, which is not an issue if it works elsewhere. Thanks
