### ISSUE TITLE
[Request] Icons-only Layout for Vertical

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#25]
Like the horizontal modes (multiple and single widgets) show only the icons, with the section title displayed on the left. could we get a similar "icons-only" layout for the vertical mode? I would think that the section title would then be displayed at the top, where it currently says "Home".

**Comment by jurialmunkey** [comment]
Interesting idea. However, the small slide over by only having icons makes it feel a bit off. Plus too many options..
