### ISSUE TITLE
[Request] [Question] Mini Landscape Layout

### ISSUE THREAD

**Issue by AERegeneratel38** [jurialmunkey/skin.arctic.zephyr.2#253]
I was customizing AZ2 to create a google tv -like skin. Is there any way I can edit any aspects available to create the mini-curved rectangles (like in the 'Your Apps' section in the image below)? If its not possible, could you please add this aspect in the skin? I believe it would be nice.

![image](https://user-images.githubusercontent.com/44703575/108622269-b0b06f00-745f-11eb-93c3-6c6279822fbc.png)

**Comment by drinfernoo** [comment]
Use a submenu widget with images for the shortcuts 👍

**Comment by AERegeneratel38** [comment]
Can't I get that submenu size icon in the home menu item directly below the widgets?
