### ISSUE TITLE
Missing context menu on individual episodes

### ISSUE THREAD

**Issue by scsmartt** [jurialmunkey/skin.arctic.zephyr.2#257]
I can pull up a context menu for an entire season or show but not on a single episode from within a season.

**Comment by drinfernoo** [comment]
If you're using a "combined" season/episode view, that is actually a limitation of the Kodi skinning engine, and can't be done. You can enter the season to open the context menu on a single episode.

**Comment by scsmartt** [comment]
I apologize. I meant to post this for Horizon.
