### ISSUE TITLE
Option to show episodes as S09E02 instead of 9x2

### ISSUE THREAD

**Issue by Joostzilla** [jurialmunkey/skin.arctic.zephyr.2#26]
For TV shows the way episodes are named is for example 9x2 for season 9, episode 2.
Honestly i like format S09E02 better. Could this be an user option?

The season could be left out of the actual list. The season number would be nice above the description

**Comment by jurialmunkey** [comment]
I use the 00x00 format for multiple reasons:
1. It works for all languages (i.e. in some languages, the words for season/episode don't start with s/e).
2. Kodi forces that format in some areas, so I like the format to be consistent.
3. It stops confusion with specials - Kodi automatically adds an S to the episode number of a special.
