### ISSUE TITLE
[Request] Settings Widget

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#3]
Would it be possible to get a Settings widget that simply acts like the Settings hub as it stands now? I'm really missing the way it worked in Aura.

**Comment by jurialmunkey** [comment]
Yeah this is planned.

**Comment by drinfernoo** [comment]
Forgive me if I open too many issues... I'm really digging this skin and hope to be using it as my primary soon.

**Comment by jurialmunkey** [comment]
No, not a problem at all! Having issues listed on github is actually much easier to keep track of than on the forums.

**Comment by jurialmunkey** [comment]
Added.
https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/bf2ff8a54b2472703acc4da8fd4c401c39c925a4
