### ISSUE TITLE
[Idea] place actor images in circle mask

### ISSUE THREAD

**Issue by Joostzilla** [jurialmunkey/skin.arctic.zephyr.2#30]
For music artist you have the option to show them in a circular or square mask.
I think it would look awesome if the actor images were circular masked too.

https://imgur.com/c0uV4cj

**Comment by jurialmunkey** [comment]
Do you mean in the library or the info dialog?

**Comment by Joostzilla** [comment]
Okay. I don't use the music section of Kodi and I thought you use the artists in circles. So that's why I thought it would be nice in movies en series too.
But no problem. It is your skin :-)
