### ISSUE TITLE
[Bug] Submenu Widgets for IAGL Not Working

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#33]
I'm trying to create a submenu hub (not auto-generated) for my preferred IAGL sections, and for some reason, widgets from that add-on won't display as submenu widgets. I've tried the "Browse by Category" section, as well as a number of game lists, and they simply won't show up.

**Comment by drinfernoo** [comment]
I'm talking about [this IAGL](https://github.com/zach-morris/plugin.program.iagl), in case that wasn't clear 👍

**Comment by drinfernoo** [comment]
Also, I've verified that the lists *do* load when added as home screen widgets.

**Comment by jurialmunkey** [comment]
Working fine for me:
https://imgur.com/a/QqkgrMq

Or are you talking about the Custom Hub (1134)?

**Comment by drinfernoo** [comment]
@jurialmunkey No, I've got the action pointed directly at IAGL, and then am using sections for submenu widgets, but I can't see those widgets at all. I haven't updated to 0.9.28 yet, but that's what I've seen so far.

**Comment by jurialmunkey** [comment]
Can you provide steps to reproduce, because I can't seem to recreate the issue.

**Comment by drinfernoo** [comment]
Sorry, somehow I missed this. I'll get something up for you tomorrow.
