### ISSUE TITLE
[Bug] Last login time cutoff in Settings -> Profiles

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#35]
Just like the title says.

![image](https://user-images.githubusercontent.com/2319508/56836294-a86b5680-682b-11e9-949f-7a76a570413c.png)

**Comment by jurialmunkey** [comment]
Ah I actually just noticed this yesterday myself. Should be fixed on latest master (not in a release yet).
