### ISSUE TITLE
Submenu hub widgets not appearing per-item

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#4]
Inside of a submenu, if I set a widget for each submenu item, they don't appear. However, if I leave them blank, and set one for the submenu *as a whole* (or a global widget), I can see that one on each item I left blank.

**Comment by Sunseng** [comment]
Its working fine on me.

**Comment by jurialmunkey** [comment]
I can't replicate this issue.
Can you provide your script-skinshortcuts-includes.xml file from skin.arctic.zephyr.2/1080i/ so I can have a look at what might be going wrong.

Also what home screen layout are you using?

**Comment by drinfernoo** [comment]
@jurialmunkey This was with the multiple widget vertical layout, on whatever was live last night around 9pm PST. I haven't tried it with today's commits.

**Comment by drinfernoo** [comment]
It appears to work now. Not sure what was going wrong 😆 Thank you!
