### ISSUE TITLE
[Feature Request] Plugin ID on information page

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#41]
Would it be possible to have the plugin ID displayed on an add-on's information page? That would be awesome 👍

**Comment by jurialmunkey** [comment]
Will do.

**Comment by jurialmunkey** [comment]
Added https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/7ce28ffc323f4e2c38698b430a39e982b9bb0401
