### ISSUE TITLE
[Bug] Widget Title Missing After Playback

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#42]
Often, after I've played something from a widget and returned to the homescreen, I come to find the titles of *content* of my widgets are all missing. It still shows the title of the widget, but with nothing following.

I don't really have a super-reliable way of reproducing it, because I often don't notice right away, and it doesn't usually bother me enough to close/reload Kodi just to fix it... so I'm not even really sure which of them does 😂

Have you experienced this at all?

**Comment by jurialmunkey** [comment]
I haven't encountered this issue. If you figure out how to reproduce it, let me know and I will investigate.

At least you don't have the issue I have on LibreElec 9 where all text disappears from the skin after playing some 1080p hevc videos until I turn my tv off then on again - that's a hardware issue though: kodi just hates the old Radeon HD 5450 that's in my HTPC.

**Comment by jurialmunkey** [comment]
Have you discovered any way to reproduce this issue yet?

**Comment by drinfernoo** [comment]
I haven't had time to test it more thoroughly, but I'll get the latest updates up soon and see what I can figure out.

**Comment by jurialmunkey** [comment]
No worries and no rush! Just thought maybe you had forgotten about it (and I haven't been able to reproduce it so far).

**Comment by milnash** [comment]
I have the same issue. Way to reproduce for me:

1. Have a widget for example "On Deck" (from PlexKodiConnect). 
2. Play an episode. 
3. The widget still shows the name of the widget, in my case "On Deck" but next to the title, it does not show the title of the selected episode. 
4. Reload skin and it shows.

Don't know if it is the skin or add-on causing this. 

Thank you for this awesome skin!

**Comment by loeffelpan** [comment]
Something similar here.
I use default widgets for unwatched movies and movie infos (year, rating, ...) are gone when the widget entry gets unfocused due to minimal busy indicator. Is this related or should I open a new isssue?

**Comment by jurialmunkey** [comment]
Related to this bug in core:
https://github.com/xbmc/xbmc/issues/15348
