### ISSUE TITLE
[Bug] Next aired dates are not consistent.

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.zephyr.2#45]
Next aired dates don't follow the system date/time settings. There are also issues with incorrect info being given by next aired.

**Comment by bartolomesoriano** [comment]
@jurialmunkey , I have found this to be the case when using the 7.0.1 version of tv.show.next.aired. If you use the 6.0.15 version from the Kodi repo, you should get consistent results.

**Comment by jurialmunkey** [comment]
Ah that makes sense. Unfortunately it looks like marcelveldt is no longer actively maintaining nextaired, so I guess the official repo version is the one to support for the time-being until someone else picks it up.
