### ISSUE TITLE
Widget limit labels

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#5]
I don't think you need the `$NUMBER` labeling for these?

https://github.com/jurialmunkey/skin.arctic.zephyr.2/blob/2d87762fe3947a2ceb46dee264706ee0c935d397/shortcuts/overrides.xml#L93-98

They show up in the skin shortcuts dialog exactly as shown in those lines, "$NUMBER[10]", etc...

**Comment by jurialmunkey** [comment]
If I don't put $NUMBER[] kodi tries to localize the labels 
e.g. Kodi turns "25" in $LOCALIZE[25] which is "May"

**Comment by drinfernoo** [comment]
Hmm... ok then.

**Comment by jurialmunkey** [comment]
Actually just found a solution to this issue. If I put a space after the number in the label, it will trick Kodi into thinking it is plain text and not a localized string.
https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/839f5cb72f8bd48020bcf536e56d5a52f4ce6bc7
