### ISSUE TITLE
[Request] Move position of End Time on OSD to improve accessibility for 6 button remote users.

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.zephyr.2#52]
The end time on the OSD is not accessible by six button remote users that only have OK and BACK buttons. OK opens OSD controls, which obscure end time. Pressing UP shows info, but lacks end time. Showing when paused is not a suitable solution. 

Potential Fix: Move End Time to Info Line. However, what to show in previous space occupied by end time? Perhaps chapters?

**Comment by baxter300** [comment]
I might be alone in this but I liked the location in AZ 1, which meant not having to go to the info section to view the end time

**Comment by drinfernoo** [comment]
This is made even worse by the Shield remote, which only has *three* function buttons: OK, Back, and Home (plus four directions and Voice).

Could it be put on the bottom left where the "Now Playing..." label is shown? Or perhaps just above the codec logos?

**Comment by jurialmunkey** [comment]
Resolved.
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.49-alpha5
