### ISSUE TITLE
[Request] Show libreelec config option instead of Event Log (if on Libreelec)

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.zephyr.2#54]
Event Log isn't that useful for most users. LibreElec Config is likely to be accessed far more frequently. Use a condition to check for the libreelec config addon.

**Comment by coz2001** [comment]
And Coreelec if possible, thanks.

**Comment by jurialmunkey** [comment]
Added:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.49-alpha3
