### ISSUE TITLE
[Request] Use ratings from listitems first if available

### ISSUE THREAD

**Issue by vitorp07** [jurialmunkey/skin.arctic.zephyr.2#57]
https://github.com/jurialmunkey/skin.arctic.zephyr.2/blob/c09803d218bdaed781de47b3780415f72c64ca6b/1080i/Includes_Object.xml#L814-L822

Would it be possible to use ratings from listitems first if available and have skin.helper as a fallback?
Maybe by adding something like this below to the list above;
i.e. 
```
<param name="tvdb_listitem" default="ListItem.Rating(tvdb)" />
<param name="tmdb_listitem" default="ListItem.Rating(tmdb)" />
<param name="imdb_listitem" default="ListItem.Rating(imdb)" />
...etc.
```
I'm passing most of these ratings already in my addon with;
```
setRating('tmdb', info['tmdbrating'], info['tmdbvotes'])
setRating('imdb', info['imdbrating'], info['imdbvotes'])
setRating('tvdb', info['tvdbrating'], info['tvdbvotes'])
setRating('trakt', info['traktrating'], info['traktvotes'])
```
and I prefer using these instead of having skin.helper running in the background.

**Comment by vitorp07** [comment]
For reference here is a screenshot when browsing in my addon without skin.helper installed, with the code above added and using by ***_listitem instead of ***_prop

![example](https://user-images.githubusercontent.com/24560096/57965913-dfa7c180-7918-11e9-8b11-2526bfa9c392.jpg)

**Comment by jurialmunkey** [comment]
Problem is that it doesn't work with the kodi library. ListItem.Rating(rating) only works in info dialog for library.

**Comment by vitorp07** [comment]
I understand that and I also like universal solutions rather than having features working here but not there...
Since I use this skin exclusively because it is pretty much a work of art, I was just wondering what to go for with my addons, so if ListItem.Rating(rating) is not an option I will simply pass imdb's ratings and votes through infolabels and remove the extra kodi's api calls for setRating().

Thanks @jurialmunkey for your skins work, you can close this.

**Comment by vitorp07** [comment]
@jurialmunkey 
I tested this again and maybe it wasn't working before but on Kodi 18.3 ListItem.Rating(rating) works properly for library items as long as the proper term are used for the ratings i.e. (themoviedb, imdb...) which all the scrapers used during my testing did.

I tried different scenarios with themoviedb scraper, universal movie scraper and my own python scraper that I'm currently working on which creates the nfo files to be scanned with the local information only scraper, with skin.helper.service and script.metadatautils enabled or disabled, with single, multiple or no ratings provided in the nfo file and at the end I've come to the conclusion that everything works as expected.

Here is 2 examples with 4 items added to the library, one using themoviedb scraper(default settings), another using universal movie scraper(default settings), and 2 using my own python scraper one of which has the ratings tag populated while I removed the ratings on the other one for testing.

This is with skin.helper.service and script.metadatautils enabled;
![skin helper service-enabled](https://user-images.githubusercontent.com/24560096/63622509-f8351100-c5c4-11e9-9eae-31ac57bfe56c.gif)

with proper visibility conditions, skin.helper.service do not interfere with the ratings provided.

---------------------------------------------------------------------------------------------------------------

This is with skin.helper.service and script.metadatautils disabled;
![skin helper service-disabled](https://user-images.githubusercontent.com/24560096/63622075-a5a72500-c5c3-11e9-8f2e-fcb81e5e9bc6.gif)

skin.helper.service fetches the missing tmdb rating where not provided.


If you're willing to test this, I've prepared a folder containing the 4 movie items with strm file containing the youtube plugin trailer and already with the nfo files present(exported via Kodi's export library),  which you can simply unzip and add them all using the local information only movie scraper.

The zip with the movie items;
https://github.com/vitorp07/tests-samples/blob/master/ListItem.Rating(rating).zip

The Includes_Object.xml file containing only the necessary changes for tmdb + imdb ratings;
https://github.com/vitorp07/tests-samples/blob/master/Includes_Object.xml

If you do test this and end up being interested, I can add the missing changes for the other ratings and make a pr.

Thanks again

**Comment by jurialmunkey** [comment]
Wait, are you saying that you are getting multiple ListItem.Rating(rating) values to work in the library with 18.3? 
Last time I tested ListItem.Rating(rating) in the library, no values were returned if it wasn't the default ListItem.Rating

If it is now working, then I'll definitely look at adding these changes in.

**Comment by vitorp07** [comment]
Yes exactly, for some reason I'm having trouble getting imdb rating with Window(home).Property(SkinHelper.ListItem.Rating.IMDB but it has nothing to do with the code above since if the imdb rating is provided then Window(home).Property(SkinHelper.ListItem.Rating.TMDB will work to get tmdb rating and you will end up having multiple ratings when using ListItem.Rating(rating) even in the library.

**Comment by jurialmunkey** [comment]
> EDIT: I do get multiple ListItem.Rating(rating) even in library as long as I set them all as default in the nfo file which is strange.

The problem is that a large portion of users don't use custom nfo files and scrapers don't set this default flag. Plus I'm not sure if it would have other unintended consequences.

**Comment by vitorp07** [comment]
I tested both universal and themoviedb scraper and they did set the default flag, at least it was in the nfo when I exported the library and I added a fallback to ListItem.Rating in case the default flag is not set.
Tested this for movies and tv shows in library and addons and all good until now but I will continue testing before adding more ratings providers in.

**Comment by vitorp07** [comment]
Hi @jurialmunkey,
I just saw this commit you recently pushed for the [ratings logo](https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/421ac2aa6b652b5a2e1314eab27077f253e77d33).
I find that it does make sense and also like that solution.
Thanks, I will close this issue now.
