### ISSUE TITLE
[Bug] Episode title missing when episode is selected from Android TV homescreen

### ISSUE THREAD

**Issue by spauldhaliwal** [jurialmunkey/skin.arctic.zephyr.2#58]
When selecting a tv episode from android tv's home screen using kodi's newly added channels support, the title is missing in the info dialog. This bug doesn't appear for movies, only tv episodes.

**Comment by jurialmunkey** [comment]
Does this happen in Estuary?

**Comment by spauldhaliwal** [comment]
Just tested and the bug is not present in Estuary.

**Comment by jurialmunkey** [comment]
Hmmm, that's odd. Not sure what would be causing it. When I have some time I'll look into what I'm doing different from Estuary. Seems really strange for it to be a skin issue though, but I guess if it works properly in Estuary then it must be a skin issue.

**Comment by jurialmunkey** [comment]
Closing this issue for now as I don't have an Android TV device to test with and I can't see what would be causing this issue.
