### ISSUE TITLE
[Request] Display Current Path in File Explorer

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#6]
In Aura, the explorer dialog used to show the current path at the bottom:

![image](https://user-images.githubusercontent.com/2319508/54882828-44640580-4e1b-11e9-88a7-ef8d2e010e0d.png)

Could we get similar functionality back?

**Comment by jurialmunkey** [comment]
I'll add this. Just leaving a comment to remind myself that I also need to add it to the subtitles download dialog.

**Comment by jurialmunkey** [comment]
Done.
