### ISSUE TITLE
[Request] Use show poster artwork for episodes in widgets rather than season poster

### ISSUE THREAD

**Issue by jsahlen** [jurialmunkey/skin.arctic.zephyr.2#60]
@jurialmunkey you wrote (in #37):

> Yeah I agree about tvshow posters being better for widgets. I'm just trying to avoid overly complex variables that only apply to the home screen (there are a ton of edge-cases that pop-up when applying different approaches to the home screen only.

I understand that this would be complex to implement, but I would like to make a formal request anyway, as I think it could be worth the effort when there's time. I find that season posters are often quite lacking in finish, and using show posters instead would make the home screen look much more uniform and refined.

Love this skin by the way—it's quickly become my default. Love the simplicity, and the scale of the UI is perfect for 55" :)

**Comment by jurialmunkey** [comment]
Fixed in 0.9.47-a2
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.47-alpha2
