### ISSUE TITLE
[Bug] Broken labels in some views

### ISSUE THREAD

**Issue by loeffelpan** [jurialmunkey/skin.arctic.zephyr.2#61]
Please fix the broken labels in some views.

- Infoline in the Lovefilm view (only if content is a tv show)
https://ibb.co/jfnC2tW

- Infoline in the Tripane view (only if content is a tv show)
https://ibb.co/Cs5Zhjn

**Comment by jurialmunkey** [comment]
I'm pretty sure this has been fixed. At least I cannot reproduce anymore.
