### ISSUE TITLE
[Bug] Notifications on Home menu

### ISSUE THREAD

**Issue by DerGary** [jurialmunkey/skin.arctic.zephyr.2#65]
hello jurialmunkey,

I currently don't see some Notifications (what's the currently playing music or when the database gets refreshed) when I am on the home menu. Some other notifications I do see on the homescreen, like when an external device gets plugged in or when the CEC gets connected. When I am in the Movie View I do see the currently playing music on the left bottom corner.

Here are my home screen settings
![screenshot000](https://user-images.githubusercontent.com/4302467/58759458-9bc4d700-852a-11e9-80f0-2e263ab3bbc3.png)

**Comment by jurialmunkey** [comment]
Thanks for reporting this issue. It's on my radar. I've been in the midst of moving house, so haven't had much free time lately - but I will try to get to it soon.

**Comment by jurialmunkey** [comment]
Extendedprogress notifications added in 
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.49-alpha7

Nowplaying notifications will come later.
