### ISSUE TITLE
[Request] Proper color of the seperator

### ISSUE THREAD

**Issue by loeffelpan** [jurialmunkey/skin.arctic.zephyr.2#66]
Said this in forum, too.
But not to be forgotten:
Please color the seperator dot of the "time-label" the same way as in other labels.

https://ibb.co/V982NK6
https://ibb.co/QY00sxz

**Comment by jurialmunkey** [comment]
Should be fixed in v0.9.46-a6
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.46-alpha6

**Comment by loeffelpan** [comment]
Thanks. But why do you use • instead of | ?
| is used as seperator in nearly any case. Why not in OSD labels, too?
