### ISSUE TITLE
[Bug] Show parent poster when series poster not available

### ISSUE THREAD

**Issue by spauldhaliwal** [jurialmunkey/skin.arctic.zephyr.2#68]
When a TV season has recently been released, or started airing, very often there is not a TV Season poster available yet, so kodi/the skin is showing the default one. It would be great if in this scenario the skin could default to the Series Poster instead.

**Comment by jurialmunkey** [comment]
Thanks for the bug report - I'll look into it once I get a few of the older issues checked-off.

**Comment by jurialmunkey** [comment]
Is this issue still happening? If it is, I'm not sure if it is possible to fix.
