### ISSUE TITLE
[Feature Request] show light / dark theme based on time of day

### ISSUE THREAD

**Issue by jonesthefox** [jurialmunkey/skin.arctic.zephyr.2#69]
It would be cool, if the skin shows the dark or light theme based on time of day or actual sunset/dawn of your region.

**Comment by jurialmunkey** [comment]
See latest release:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.35-alpha1

Unfortunately the System.Time conditional doesn't accept variables or user inputted values, so the times are hardcoded to 6am and 6pm. The theme will switch when returning to the home screen between those times.

Skin Settings > Miscellaneous > Automatically switch color theme
