### ISSUE TITLE
[Bug] Custom Genre Hub Displays Icon *and* Label

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#7]
I'm playing around with custom hubs, and when setting one for the Genres node in my library:

![image](https://user-images.githubusercontent.com/2319508/54882994-83935600-4e1d-11e9-96df-72589ec707c8.png)

The submenu in the hub shows both icons *and* text labels:

![image](https://user-images.githubusercontent.com/2319508/54883002-960d8f80-4e1d-11e9-940e-f8b871d98c40.png)

Also, is there any list of other windows we can use for hubs? I noticed that by default, there are a few already in the menus:

1133 for movie sets, 1132 for movie genres, 1131 for movie years, and 1135 for TV genres are the ones I was seeing.

**Comment by jurialmunkey** [comment]
Yeah this should be text only. I've fixed it now.
1132 is more suitable for movie genres than using the custom hub.

Yep you've got all of them. Except 1135 is the submenu hub.

**Comment by drinfernoo** [comment]
Is it possible to make those easier to access through the menu, rather than remembering which one to activate?

**Comment by jurialmunkey** [comment]
Yeah, I will be adding some shortcuts. I need to make a few modifications to those windows first though - I'm planning to have it be possible to choose whether the genre/decade hubs are movies/tvshows/music

**Comment by drinfernoo** [comment]
@jurialmunkey What other special shortcuts do you think would be useful?
