### ISSUE TITLE
Collection / movie sets info screen

### ISSUE THREAD

**Issue by Sjors125** [jurialmunkey/skin.arctic.zephyr.2#71]
I would very much like to have a movie collection/sets info screen, as is part of the AZ Plus Mod.
See this post from the AZ2 topic: https://forum.kodi.tv/showthread.php?pid=2857264#pid2857264
More examples in the AZ Plus Mod topic: https://forum.kodi.tv/showthread.php?tid=307462

Preferably, it works with custom made collections too.
Like a Middle Earth Collection, MCU Phase One Collection or James Bond Collection (including Never Say Never Again, etc)

Thanks for creating this!

**Comment by jurialmunkey** [comment]
Movie Sets Info is actually being added to Kodi v19, so I'm going to wait for that rather than add a stop-gap solution.

https://github.com/xbmc/xbmc/pull/15315

**Comment by Sjors125** [comment]
That’s quite understandable. Hope it will look good, or gives you enough skinning options.
Thanks for your reply. 😊

Van: jurialmunkey <notifications@github.com>
Verzonden: zondag 7 juli 2019 14:11
Aan: jurialmunkey/skin.arctic.zephyr.2 <skin.arctic.zephyr.2@noreply.github.com>
CC: Sjors125 <jorgenbrouwer@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [jurialmunkey/skin.arctic.zephyr.2] Collection / movie sets info screen (#71)


Movie Sets Info is actually being added to Kodi v19, so I'm going to wait for that rather than add a stop-gap solution.

xbmc/xbmc#15315<https://github.com/xbmc/xbmc/pull/15315>

**Comment by jurialmunkey** [comment]
Actually I had another look at it was really simple to achieve v18, so I've added a sets info page to latest release (v0.9.37). Still quite a few things to add to it and tweak, but it works.

**Comment by Sjors125** [comment]
Thanks jm!

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
