### ISSUE TITLE
[Request] Add more view types to AEL

### ISSUE THREAD

**Issue by MitchZombie** [jurialmunkey/skin.arctic.zephyr.2#73]
Add more view types to Advanced Emulator Launcher add-on.

**Comment by SoulFear** [comment]
Would absolutely love to see more AEL views!

**Comment by jurialmunkey** [comment]
Latest release should open up more AEL views.
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.52-alpha4

Can you test and confirm. I don't use AEL and I don't have it setup to test myself.

**Comment by MitchZombie** [comment]
Fantastic ! 
Had a little play with it, only problem I could see is the Icon Wall view. 

https://imgur.com/0559X3m

Thank you jurialmunkey for your time adding this !!!
