### ISSUE TITLE
[Request] Circular Widget Scrolling

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#75]
I'm wondering if it would be possible to get wom circular scrolling for widgets. Ideally, it would work both horizontally *and* vertically (possibly with settings to customize the behavior), allowing you to "endlessly" scroll a single widget horizontally, and through your defined widgets in the same way.

For example, a set of widgets like this:

* Recommended

* Genres

* In Progress

Would be able to scroll through repeatedly, going Recommended -> Genres -> In Progress -> Recommended -> Genres -> In Progress -> etc...

When wanting to return to the "beginning" of the list, the list wouldn't be able to scroll "backwards", if that makes sense, and would stop on the far left or top of the list.

I hope that makes sense. It'd be an interesting way to get a more seamless browsing experience similar to other popular streaming platforms like Netflix and Hulu 👍

**Comment by jurialmunkey** [comment]
Hmmm. Horizontal wrap is easy, but vertical repeat of widgets is difficult. I could return focus to the top when you reach the bottom, but that doesn't really have the same infinitely repeating style of widgets.

I'll have a bit of a think about how I might achieve this vertical repeating and get back to you.

**Comment by jurialmunkey** [comment]
Meta issue for home animations:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/114

**Comment by jurialmunkey** [comment]
Meta Issue:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/115
