### ISSUE TITLE
submenu hub in vertical menu

### ISSUE THREAD

**Issue by bibiyanki** [jurialmunkey/skin.arctic.zephyr.2#77]
hello.
it's possible to show a littler submenu hub ,where widget appear? it's more easily for use.(in vertical menu)
best regard

**Comment by chiefkes** [comment]
Seconded

**Comment by SeeThisIsMe** [comment]
If this is like the arctic zephyr v1 vertical submenus, then definitely I will give a 3rd vote for this option.

![image](https://user-images.githubusercontent.com/53046241/61456954-9cdd8680-a967-11e9-8c9c-33c4f15adcb0.png)

**Comment by jurialmunkey** [comment]
@SeeThisIsMe - I think they are talking about for the multiwidget layouts, not the basic layout. Basic layout submenu will not change as it is integrated with the submenu hub, which is a key feature of AZ2 in basic layout.

For multiwidget layouts, some sort of change to the submenu presentation is a definite maybe, as I find the current implementation a little un-intuitive.

**Comment by drinfernoo** [comment]
I don't know that it's exactly what we're looking for, but in #8, I had proposed a change that would basically make all of the submenus "slide out" in two stages, similar to how they work in "Basic" mode now, but for any of the skin layouts.

**Comment by jurialmunkey** [comment]
Meta issue for home menu animation improvements:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/114
