### ISSUE TITLE
how modified skinshortcut-include.xml

### ISSUE THREAD

**Issue by bibiyanki** [jurialmunkey/skin.arctic.zephyr.2#78]
hello:

i have find soluce for multisearch but i must modified skinshortcut-include.xml

when i try to modified, and reload skin, the xml backup old modification, please help me to modified this xml

thank u

**Comment by jurialmunkey** [comment]
you can't edit this file - it is generated by skinshortcuts addon.

**Comment by bibiyanki** [comment]
it's not possible to put search in submenu...
