### ISSUE TITLE
[Request] "Slide Out" All Submenus

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#8]
When not using the multiple widget layout, and you open a submenu by pressing down, the menu slides **up** to cover the screen, and the hub populates.

Currently, there is no animation of the horizontal menu besides the widgets "shrinking" away, and the vertical menu slides the menu **left**, but the widgets **right**.

This request is for the multiple widget layouts to have a similar behavior to the single widget layout, where the horizontal menu would slide **down**, and the vertical menu would slide **right**, before populating the submenu hub.

**Comment by jurialmunkey** [comment]
I'm not sure why I closed this issue - I think maybe I tried a few approaches but couldn't get something that I liked.

**Comment by drinfernoo** [comment]
I particularly like the way the submenu works in "Basic" mode, as a sort of "two-stage process", which I think would work fine in horizontal multi-widget... but vertical may be a bit trickier to get smooth.

I think it would be interesting if in vertical, the categories would be vertical, and you could do multiple widgets per category... a custom secondary homescreen, if you will.

**Comment by jurialmunkey** [comment]
Meta issue for home animations:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/114
