### ISSUE TITLE
[Request] More Widget Types

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#82]
After checking out the widget types available in AuraMOD, I'm wondering if something similar to these could be added to AZ2:

![LandscapePoster](https://i.imgur.com/KVKRH81.png)
![PosterDetails](https://i.imgur.com/4XapiPk.png)

In these, the bulk of the items are Poster, but the focused item gets shifted to Landscape, with either landscape artwork, or plot and other metadata about the item.

I wanted to try and add these myself, but can't find where this skin defines widgets?

**Comment by michielvandenboogaart** [comment]
I've recently modded those widgets myself. The place you're looking for is in the IncludesObject,

Look for the include with the name "Object_Widget_Spotlight". Below that, you'll see some itemlayout and focusedlayout. Each type like square, icon, landscape has it's own set of itemlayout and focusedlayout. It's the focuslayout you want to extend.

I'm a beginner and a total n00b with skinning and have just started modding a skin. You can look at my modifications, maybe it helps you with the modifications you want. 

https://github.com/michielvandenboogaart/skin.arctic.zephyr.2

**Comment by jurialmunkey** [comment]
This looks like an interesting idea. Is it a fixedlist (i.e. first item is always focused) or a normal list? 
I'm assuming fixedlist as that would work much better. 

Only thing is that I would need to change all the other widget types to fixedlist too to maintain consistency of user experience. Changing them to fixedlist is not necessarily a bad idea either, as it probably makes sense considering most other tv app UIs use fixedlists (e.g. Netflix, Roku etc.)

**Comment by drinfernoo** [comment]
@jurialmunkey Those are screenshots from AuraMOD, and he has made a setting to turn on and off fixed scrolling. Could that be a potential future for AZ2 as well?

**Comment by jurialmunkey** [comment]
A toggle between fixed/normal would probably be good. I've got to get everything consistent first, though! At the moment there is a fair bit of inconsistency between list scroll types.

**Comment by jurialmunkey** [comment]
Meta Issue:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/115
