### ISSUE TITLE
[Request] Alternative weather fanart?

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#86]
Currently, it appears you can *only* use "Weather Fanart - Multi" with AZ2. Any way to make it configurable?

**Comment by jurialmunkey** [comment]
Not really. The available packs are not consistent in their structure

Fanart multi uses folders - i.e.
ResourceName/FanartCode/XX.jpg

Whereas others use filenames for fanart code:
ResourceName/FanartCode.jpg

Or some will use png instead
ResourceName/FanartCode.png

The layout of the image resource is almost impossible to check for other than just checking against the name and maintaining a list of all the resources, which is a complete pain to manage in the skin.
