### ISSUE TITLE
[Request] Support for add-on news

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#87]
Kodi provides a way to to include "news", often a changelog, in add-ons' `addon.xml` files, by way of the `<news>` tag. Is there any way to get that information to show in the Information dialog, similar to how Aura did?

**Comment by jurialmunkey** [comment]
This was actually already possible by pressing up in AddonInfo.
Nonetheless, I've added it to the main "plotbox" section of the AddonInfo dialog.
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.49-alpha8
