### ISSUE TITLE
[Request] Actor Search in "Global Search"

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#9]
I'm really loving the built in search features in this skin, but am curious if you can add specific actor search... rather than just "Movies with X". Is that possible with the current setup, or am I reaching?

**Comment by jurialmunkey** [comment]
Unfortunately it doesn't seem to be possible. I really wanted something like this too - the "Movies with X" was the best I could figure. 

Basically, I can pretty much do anything that you can do with a library node. Haven't been able to find a way yet to only show actors in a library node that match a certain label.
