### ISSUE TITLE
[Request] Different views for pause and skip in OSD

### ISSUE THREAD

**Issue by brandbrilliance** [jurialmunkey/skin.arctic.zephyr.2#90]
If you set up poster and info to display on the pause menu, it also shows when you skip. Perhaps a setting to allow it to show a minimal view when skipping. I also noticed that the OSD return takes 1 second even though it’s unset in the Skin setting.

**Comment by jurialmunkey** [comment]
I don't understand what you mean by "OSD return takes 1 second"???

**Comment by brandbrilliance** [comment]
Here is a short video of how long it takes to return back to full screen after you hit unpause. It's actually not 1 sec but about 2secs. Hope that helps.

https://drive.google.com/file/d/1Nuh8ylxQghf6E5AmrTMYCgzbKhe_HedI/view?usp=sharing

**Comment by jurialmunkey** [comment]
That's intentional. I don't know what skin setting that you're talking about, because there isn't a setting related to how long the osd info displays for. After unpausing or seeking, Kodi sets a DisplayAfterSeek flag for a short amount of time. The osd info displays until the flag isn't set anymore.

**Comment by brandbrilliance** [comment]
The first part for two settings would still be valid as it would be nice to have the full info come up on pause but have a minimal view when skipping. 

Ps. About the  delay you speak of, is there a way for Kodi to turn that off?

**Comment by jurialmunkey** [comment]
Seek issue fixed:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.52-alpha3

**Comment by brandbrilliance** [comment]
Installed and tested. Thanks!!! Works perfectly!!!
