### ISSUE TITLE
[Bug] Different widget aspects don't work in submenu widgets

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#91]
It seems no matter which aspect I use for submenu widgets, they always appear as "Poster".

**Comment by drinfernoo** [comment]
I stand corrected... "Square" also works.

**Comment by jurialmunkey** [comment]
Only large versions work for submenu hub due to sizing. The new widget types won't work. I have to figure out a way to hide those options for submenu hubs (the management of submenu hubs needs an overhaul in general).

**Comment by jurialmunkey** [comment]
Pretty sure I fixed this a few releases ago, so closing the issue.
