### ISSUE TITLE
[Request] 'see more' at the end of each widget

### ISSUE THREAD

**Issue by Dealz-416LS** [jurialmunkey/skin.arctic.zephyr.2#95]
'See more' item at the end of each row of widgets, allows quick access to the widget's source. Useful when each row of widgets is limited to 10.

**Comment by willhowlett** [comment]
+1 for this feature! (would be good if the link was customisable, i.e. it was able to go to somewhere else other than the widget source)

**Comment by jurialmunkey** [comment]
Meta Issue:
https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/115
