### ISSUE TITLE
[REQUEST] TMDB Helper Additional Feature Trakt

### ISSUE THREAD

**Issue by starman2908** [jurialmunkey/skin.arctic.zephyr.2#96]
Hey,

KUDOS!!!

Absolutely love the new feature of the TMDB helper add-on. It works really well and hopefully will negate the use of extended info and beta skin helper service. 

I was wondering about the possibility of integrating Trakt features, allowing for the authentication and retrieval of user watchlist and custom created lists. There's a plethora of third party (questionably legal addons) that have integrated Trakt authentication and could probably have their code 'borrowed' lol. But it would be great to see a legit addon integration, even if it is only a link to search local library like that already exists in the TMDB addon online info dialogs. 

Thanks for your consideration and all the time you spend on AZ2, it is really appreciated.

**Comment by drinfernoo** [comment]
This should be an issue here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper

**Comment by starman2908** [comment]
Whoops, Cheers Doc
