### ISSUE TITLE
[Request] PVR view options

### ISSUE THREAD

**Issue by sabre6** [jurialmunkey/skin.arctic.zephyr.2#97]
Hi, I think some of these you say are in the works in the forum, but just wanted to get them on this list.  

-In Guide, allow an option to see show information when browsing the guide, either at top or bottom (great for sports).  
-In Guide, ability to see if show is First Run (New) w/ an indicator in grid
-Home page, have a message area for next recording/active recording. 

Thank you

**Comment by jurialmunkey** [comment]
> In Guide, ability to see if show is First Run (New) w/ an indicator in grid

Do you know any skins that show this information? I'm not aware of any pvr infolabel that indicates first run.

**Comment by drinfernoo** [comment]
Dunno if it goes here, but I'd really like a quick way to switch from channels to guide...

**Comment by sabre6** [comment]
> > In Guide, ability to see if show is First Run (New) w/ an indicator in grid
> 
> Do you know any skins that show this information? I'm not aware of any pvr infolabel that indicates first run.

Pretty sure i saw this in guides in the past (maybe Titan), but yeah, dont see it in estuary.  i guess if we have info box, we could just need "new" in there.

**Comment by michaelarnauts** [comment]
> -In Guide, allow an option to see show information when browsing the guide, either at top or bottom (great for sports).

I would love this also.

**Comment by jurialmunkey** [comment]
Added info option for guide.
Added quickjump from tvchannels menu to other pvr sections
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.48-alpha1

**Comment by michaelarnauts** [comment]
> Added info option for guide.
> Added quickjump from tvchannels menu to other pvr sections
> https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.48-alpha1

@jurialmunkey Nice! The "show info" setting is reversed however. It is shown when it is unchecked. :)

**Comment by jurialmunkey** [comment]
> 
> 
> > Added info option for guide.
> > Added quickjump from tvchannels menu to other pvr sections
> > https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/v0.9.48-alpha1
> 
> @jurialmunkey Nice! The "show info" setting is reversed however. It is shown when it is unchecked. :)

Hahaha, whoops! I didn't even notice that it was the wrong way around. Thanks. Should be fixed now.

**Comment by michaelarnauts** [comment]
@jurialmunkey Great! I've just noticed you also made the same mistake with the "channel numbers" option. :)

**Comment by sabre6** [comment]
great, thanks so much.

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey Great! I've just noticed you also made the same mistake with the "channel numbers" option. :)
🤦‍♂ 
Fixed.
