### ISSUE TITLE
[Bug] Clearlogo Inconsistency

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#98]
I've been playing around with the combination of "Clearlogo" and "Landscape art", and it seems there's a bit of inconsistency with TV episodes specifically.

If I have clearlogo enabled, but landscape art disabled, I see a clearlogo in the header *and* on the thumbnail, as expected.

Whenever I enable landscape art, I get a clearlogo in the header, but *not* on the thumb. Again, this makes sense, since landscape art often includes the logo directly in the artwork.

These seem to work perfectly for movies, shows, and seasons.

**However**, it seems that for episodes, I get clearlogo on the thumb no matter which combination of settings I use. I don't know if that's intended, but it seemed inconsistent to me...

**Comment by drinfernoo** [comment]
You know what... Maybe I'm just misinterpreting the settings. It appears that the "Clearlogo" setting *only* controls the clearlogo at the top of the screen. The clearlogo on thumbs is active at all times, unless using "Landscape art", and on all episodes.

I'll close this as I guess this is expected behavior, but I'll admit I was a bit confused at first.

**Comment by jurialmunkey** [comment]
Yeah, you are correct about the options. Furniture options only control what is around the edges of the screen (i.e. the screen "furniture"), not what happens with individual items.

The clearlogo is always overlayed the episode thumb to make it clearer what tvshow the thumb is from (useful for recently added episodes widgets or other episode widgets that mix multiple shows together).
